version: "3"
services:
  test_database:
    container_name: mysql
    image: mysql:5.7
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306

  test_application:
    container_name: peloton-backend
    build: .
    ports:
      - 8080:8080
    depends_on:
      - test_database
